# Generated by Django 3.0.2 on 2020-01-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ucenik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=20)),
                ('Prezime', models.CharField(max_length=20)),
                ('DatumRodenja', models.DateField()),
            ],
        ),
    ]
